# Generated by Django 2.0.2 on 2018-03-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20180323_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='good',
            name='availability',
            field=models.BooleanField(db_index=True, default=True, verbose_name='В наличий да/нет'),
        ),
        migrations.AddField(
            model_name='good',
            name='brand',
            field=models.CharField(max_length=15, null=True, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='good',
            name='img2903701',
            field=models.CharField(max_length=15, null=True, verbose_name='Изображение - 290x370-1'),
        ),
        migrations.AddField(
            model_name='good',
            name='img2903702',
            field=models.CharField(max_length=15, null=True, verbose_name='Изображение - 290x370-2'),
        ),
        migrations.AddField(
            model_name='good',
            name='img5557101',
            field=models.CharField(max_length=15, null=True, verbose_name='Изображение - 555x710-1'),
        ),
        migrations.AddField(
            model_name='good',
            name='img5557102',
            field=models.CharField(max_length=15, null=True, verbose_name='Изображение - 555x710-2'),
        ),
        migrations.AddField(
            model_name='good',
            name='img5557103',
            field=models.CharField(max_length=15, null=True, verbose_name='Изображение - 555x710-3'),
        ),
        migrations.AddField(
            model_name='good',
            name='img5557104',
            field=models.CharField(max_length=15, null=True, verbose_name='Изображение - 555x710-4'),
        ),
        migrations.AddField(
            model_name='good',
            name='img70901',
            field=models.CharField(max_length=15, null=True, verbose_name='Изображение - 70x90-1'),
        ),
        migrations.AddField(
            model_name='good',
            name='img70902',
            field=models.CharField(max_length=15, null=True, verbose_name='Изображение - 70x90-2'),
        ),
        migrations.AddField(
            model_name='good',
            name='img70903',
            field=models.CharField(max_length=15, null=True, verbose_name='Изображение - 70x90-3'),
        ),
        migrations.AddField(
            model_name='good',
            name='img70904',
            field=models.CharField(max_length=15, null=True, verbose_name='Изображение - 70x90-4'),
        ),
        migrations.AddField(
            model_name='good',
            name='img9090',
            field=models.CharField(max_length=15, null=True, verbose_name='Изображение - 90x90'),
        ),
        migrations.AddField(
            model_name='good',
            name='in_sale',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Скидка да/нет'),
        ),
        migrations.AddField(
            model_name='good',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Стоймость'),
        ),
        migrations.AddField(
            model_name='good',
            name='sale',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='good',
            name='desc',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
