# Generated by Django 2.0.2 on 2018-03-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20180327_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='img2903701',
            field=models.CharField(max_length=30, null=True, verbose_name='Изображение - 290x370-1'),
        ),
        migrations.AlterField(
            model_name='good',
            name='img2903702',
            field=models.CharField(max_length=30, null=True, verbose_name='Изображение - 290x370-2'),
        ),
        migrations.AlterField(
            model_name='good',
            name='img5557101',
            field=models.CharField(max_length=30, null=True, verbose_name='Изображение - 555x710-1'),
        ),
        migrations.AlterField(
            model_name='good',
            name='img5557102',
            field=models.CharField(max_length=30, null=True, verbose_name='Изображение - 555x710-2'),
        ),
        migrations.AlterField(
            model_name='good',
            name='img5557103',
            field=models.CharField(max_length=30, null=True, verbose_name='Изображение - 555x710-3'),
        ),
        migrations.AlterField(
            model_name='good',
            name='img5557104',
            field=models.CharField(max_length=30, null=True, verbose_name='Изображение - 555x710-4'),
        ),
        migrations.AlterField(
            model_name='good',
            name='img70901',
            field=models.CharField(max_length=30, null=True, verbose_name='Изображение - 70x90-1'),
        ),
        migrations.AlterField(
            model_name='good',
            name='img70902',
            field=models.CharField(max_length=30, null=True, verbose_name='Изображение - 70x90-2'),
        ),
        migrations.AlterField(
            model_name='good',
            name='img70903',
            field=models.CharField(max_length=30, null=True, verbose_name='Изображение - 70x90-3'),
        ),
        migrations.AlterField(
            model_name='good',
            name='img70904',
            field=models.CharField(max_length=30, null=True, verbose_name='Изображение - 70x90-4'),
        ),
        migrations.AlterField(
            model_name='good',
            name='img9090',
            field=models.CharField(max_length=30, null=True, verbose_name='Изображение - 90x90'),
        ),
    ]
