# Generated by Django 2.0.2 on 2018-03-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20180327_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикация'),
        ),
    ]
