# Generated by Django 2.0.2 on 2018-03-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_good_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикация'),
        ),
    ]
